server:
  port: ${PORT:8080}

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: false
    cors:
      allowed-origins: http://some.domain.com
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
  static:
    basePath: /
  enabled: true
  pageTitle: GraphiQL
  cdn:
      enabled: false
      version: 0.13.0
  props:
      resources:
          query: query.graphql
          defaultQuery: defaultQuery.graphql
          variables: variables.graphql
      variables:
          editorTheme: "solarized light"
