package com.hrybrn.pyramid.data;

import com.jmethods.catatumbo.Entity;
import com.jmethods.catatumbo.Identifier;
import lombok.Data;

@Data
@Entity(kind="User")
public class CurrentUser {
  @Identifier(autoGenerated = false)
  private String id;
  private String name;
  private String secret;
}
