package com.hrybrn.pyramid.data;

import com.jmethods.catatumbo.Entity;
import com.jmethods.catatumbo.Identifier;
import lombok.Data;

@Data
@Entity
public class User {
  @Identifier(autoGenerated = false)
  private String id;
  private String name;
}
